const initialValues = {
  uid: "",
  workHours: "",
  title: "",
  specialCommitments: "",
  skills: "",
  salaryCurrency: "",
  responsibilities: "",
  qualifications: "",
  occupationalCategory: "",
  jobLocation: "",
  jobBenefits: "",
  industry: "",
  incentiveCompensation: "",
  experienceRequirements: "",
  employmentType: "",
  educationRequirements: "",
  description: "",
  companyInfo: "",
  companyUrl: "",
  companyDescription: "",
  companySize: "",
  companyLocation: "",
  baseSalary: "",
  contactInfo: "",
};

export default initialValues;
